#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    # Write your code here
    d1=[]
    d2=[]
    for i in range(0,len(arr)):
        for j in range(len(arr[i])):
            if(i==j):
                d1.append(arr[i][j])
            if(i+j+1 == len(arr)):
                d2.append(arr[i][j])
    result = abs(sum(d1)-sum(d2))  
    return result 
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))
     
    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
